version: '3'

services:
  nginx:
    image: 'nginx:latest'
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './app:/var/www/html'
    ports:
      - '8080:80'
    restart: 'always'
    depends_on:
      - 'php'
      - 'postgres'
  php:
    build: './php'
    restart: 'always'
    volumes:
      - './php/php.ini:/usr/local/etc/php/conf.d/php.ini'
      - './app:/var/www/html'
  phppgmyadmin:
    image: 'dockage/phppgadmin:latest'
    restart: 'always'
    ports:
      - '8090:80'
    depends_on:
      - 'php'
    environment:
      PHP_PG_ADMIN_SERVER_DESC: 'PostgreSQL'
      PHP_PG_ADMIN_SERVER_HOST: 'localhost'
      PHP_PG_ADMIN_SERVER_PORT: '5432'
      PHP_PG_ADMIN_SERVER_SSL_MODE: 'allow'
      PHP_PG_ADMIN_SERVER_DEFAULT_DB: 'template1'
      PHP_PG_ADMIN_SERVER_PG_DUMP_PATH: '/usr/bin/pg_dump'
      PHP_PG_ADMIN_SERVER_PG_DUMPALL_PATH: '/usr/bin/pg_dumpall'
  postgres:
    image: 'postgres:latest'
    restart: 'always'
    environment:
      POSTGRES_DB : 'test'
      POSTGRES_USER : 'root'
      POSTGRES_PASSWORD : 'root'
    ports:
       - '5432:5432'
    volumes:
       - './postgres/:/docker-entrypoint-initdb.d/'
